# Generated by Django 4.2.14 on 2025-08-16 01:55

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ABTestResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("hypothesis", models.TextField()),
                ("success_metric", models.CharField(max_length=100)),
                ("control_variant", models.JSONField(default=dict)),
                ("test_variants", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("95"), max_digits=5
                    ),
                ),
                ("statistical_significance", models.BooleanField(default=False)),
                (
                    "control_conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("test_conversion_rates", models.JSONField(default=dict)),
                ("total_participants", models.PositiveIntegerField(default=0)),
                ("control_participants", models.PositiveIntegerField(default=0)),
                ("test_participants", models.JSONField(default=dict)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ab_test_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAgentAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("total_interactions", models.PositiveIntegerField(default=0)),
                ("unique_users", models.PositiveIntegerField(default=0)),
                (
                    "average_response_time",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "success_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "user_satisfaction",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "cost_per_interaction",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "task_breakdown",
                    models.JSONField(
                        default=dict, help_text="Types of tasks performed"
                    ),
                ),
                (
                    "error_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "retry_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_agent_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CohortAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cohort_date", models.DateField()),
                ("period", models.PositiveIntegerField()),
                ("cohort_size", models.PositiveIntegerField(default=0)),
                ("returning_users", models.PositiveIntegerField(default=0)),
                (
                    "retention_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("launches_created", models.PositiveIntegerField(default=0)),
                ("ai_interactions", models.PositiveIntegerField(default=0)),
                (
                    "revenue_per_user",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cohort_analysis",
                "ordering": ["cohort_date", "period"],
            },
        ),
        migrations.CreateModel(
            name="ConversionFunnel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "funnel_type",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "User Registration"),
                            ("LAUNCH_CREATION", "Launch Creation"),
                            ("SOCIAL_CONNECT", "Social Media Connection"),
                            ("AI_INTERACTION", "AI Agent Interaction"),
                            ("INVESTMENT", "Investment/Purchase"),
                        ],
                        max_length=30,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "step_data",
                    models.JSONField(
                        default=dict, help_text="Step-by-step conversion data"
                    ),
                ),
                ("total_entries", models.PositiveIntegerField(default=0)),
                ("total_conversions", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "drop_off_points",
                    models.JSONField(default=dict, help_text="Major drop-off points"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "conversion_funnels",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="EventTracking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("USER_ACTION", "User Action"),
                            ("SYSTEM_EVENT", "System Event"),
                            ("CONVERSION", "Conversion"),
                            ("ERROR", "Error"),
                            ("PERFORMANCE", "Performance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=200)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("properties", models.JSONField(default=dict)),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "event_tracking",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LaunchAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("unique_visitors", models.PositiveIntegerField(default=0)),
                ("returning_visitors", models.PositiveIntegerField(default=0)),
                ("time_on_page", models.DurationField(blank=True, null=True)),
                (
                    "bounce_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "scroll_depth",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("new_interests", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("social_shares", models.PositiveIntegerField(default=0)),
                ("social_mentions", models.PositiveIntegerField(default=0)),
                ("social_reach", models.PositiveIntegerField(default=0)),
                ("direct_traffic", models.PositiveIntegerField(default=0)),
                ("referral_traffic", models.PositiveIntegerField(default=0)),
                ("social_traffic", models.PositiveIntegerField(default=0)),
                ("search_traffic", models.PositiveIntegerField(default=0)),
                ("top_countries", models.JSONField(default=dict)),
                ("top_cities", models.JSONField(default=dict)),
                ("device_breakdown", models.JSONField(default=dict)),
                ("browser_breakdown", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "launch_analytics_detailed",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "average_response_time",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "p95_response_time",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "p99_response_time",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "error_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("total_errors", models.PositiveIntegerField(default=0)),
                (
                    "cpu_usage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "memory_usage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "disk_usage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("db_connections", models.PositiveIntegerField(default=0)),
                (
                    "db_query_time",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("slow_queries", models.PositiveIntegerField(default=0)),
                (
                    "ai_service_uptime",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("social_media_api_status", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "performance_metrics",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PlatformAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("returning_users", models.PositiveIntegerField(default=0)),
                ("total_launches", models.PositiveIntegerField(default=0)),
                ("new_launches", models.PositiveIntegerField(default=0)),
                ("successful_launches", models.PositiveIntegerField(default=0)),
                ("failed_launches", models.PositiveIntegerField(default=0)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                (
                    "average_session_duration",
                    models.DurationField(blank=True, null=True),
                ),
                ("page_views", models.PositiveIntegerField(default=0)),
                (
                    "bounce_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("ai_interactions", models.PositiveIntegerField(default=0)),
                ("ai_tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "ai_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("social_posts", models.PositiveIntegerField(default=0)),
                ("social_engagement", models.PositiveIntegerField(default=0)),
                ("social_reach", models.PositiveIntegerField(default=0)),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "subscription_revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                (
                    "transaction_fees",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=15
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Platform Analytics",
                "db_table": "platform_analytics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("platform", models.CharField(max_length=20)),
                ("posts_published", models.PositiveIntegerField(default=0)),
                ("posts_scheduled", models.PositiveIntegerField(default=0)),
                ("posts_failed", models.PositiveIntegerField(default=0)),
                ("total_reach", models.PositiveIntegerField(default=0)),
                ("total_impressions", models.PositiveIntegerField(default=0)),
                ("organic_reach", models.PositiveIntegerField(default=0)),
                ("paid_reach", models.PositiveIntegerField(default=0)),
                ("total_likes", models.PositiveIntegerField(default=0)),
                ("total_comments", models.PositiveIntegerField(default=0)),
                ("total_shares", models.PositiveIntegerField(default=0)),
                ("total_clicks", models.PositiveIntegerField(default=0)),
                (
                    "engagement_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("followers_start", models.PositiveIntegerField(default=0)),
                ("followers_end", models.PositiveIntegerField(default=0)),
                ("followers_gained", models.IntegerField(default=0)),
                ("followers_lost", models.IntegerField(default=0)),
                ("best_post_performance", models.JSONField(default=dict)),
                ("worst_post_performance", models.JSONField(default=dict)),
                ("optimal_posting_times", models.JSONField(default=list)),
                ("audience_age_breakdown", models.JSONField(default=dict)),
                ("audience_gender_breakdown", models.JSONField(default=dict)),
                ("audience_location_breakdown", models.JSONField(default=dict)),
                ("top_hashtags", models.JSONField(default=list)),
                ("content_type_performance", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "social_media_analytics_detailed",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("sessions", models.PositiveIntegerField(default=0)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("page_views", models.PositiveIntegerField(default=0)),
                ("launches_created", models.PositiveIntegerField(default=0)),
                ("launches_viewed", models.PositiveIntegerField(default=0)),
                ("ai_interactions", models.PositiveIntegerField(default=0)),
                ("social_posts", models.PositiveIntegerField(default=0)),
                ("comments_posted", models.PositiveIntegerField(default=0)),
                ("likes_given", models.PositiveIntegerField(default=0)),
                ("shares_made", models.PositiveIntegerField(default=0)),
                ("conversion_events", models.PositiveIntegerField(default=0)),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_analytics",
                "ordering": ["-date"],
            },
        ),
    ]
