# Generated by Django 4.2.14 on 2025-08-16 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_agents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("analytics", "0001_initial"),
        ("launches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useranalytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialmediaanalytics",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_analytics_detailed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="launchanalytics",
            name="launch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailed_analytics",
                to="launches.tokenlaunch",
            ),
        ),
        migrations.AddField(
            model_name="eventtracking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversionfunnel",
            unique_together={("funnel_type", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="cohortanalysis",
            unique_together={("cohort_date", "period")},
        ),
        migrations.AddField(
            model_name="aiagentanalytics",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailed_analytics",
                to="ai_agents.aiagent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="useranalytics",
            unique_together={("user", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="socialmediaanalytics",
            unique_together={("user", "date", "platform")},
        ),
        migrations.AlterUniqueTogether(
            name="launchanalytics",
            unique_together={("launch", "date")},
        ),
        migrations.AddIndex(
            model_name="eventtracking",
            index=models.Index(
                fields=["category", "action"], name="event_track_categor_729757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventtracking",
            index=models.Index(
                fields=["user", "timestamp"], name="event_track_user_id_0ed4dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventtracking",
            index=models.Index(
                fields=["timestamp"], name="event_track_timesta_c57ce7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiagentanalytics",
            unique_together={("agent", "date")},
        ),
    ]
