# Generated by Django 4.2.14 on 2025-08-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Web3Nonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=42, unique=True)),
                ("nonce", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "web3_nonces",
                "indexes": [
                    models.Index(
                        fields=["address", "created_at"],
                        name="web3_nonces_address_551dce_idx",
                    )
                ],
            },
        ),
    ]
