# Generated by Django 4.2.14 on 2025-08-16 01:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIAgent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing Agent"),
                            ("COMMUNITY", "Community Agent"),
                            ("ANALYTICS", "Analytics Agent"),
                            ("LAUNCH_GUIDE", "Launch Guide Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("model", models.CharField(default="gemini-pro", max_length=50)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                ("context_limit", models.PositiveIntegerField(default=4000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("MAINTENANCE", "Maintenance"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("total_interactions", models.PositiveIntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_active", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIAgentMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_requests", models.PositiveIntegerField(default=0)),
                ("successful_requests", models.PositiveIntegerField(default=0)),
                ("failed_requests", models.PositiveIntegerField(default=0)),
                ("average_response_time", models.FloatField(default=0.0)),
                ("total_tokens_used", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("average_user_rating", models.FloatField(default=0.0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIConversationContext",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("conversation_history", models.JSONField(default=list)),
                ("context_data", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("context", models.JSONField(default=dict)),
                ("response", models.TextField()),
                ("model_used", models.CharField(max_length=50)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("response_time", models.FloatField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("user_rating", models.PositiveIntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("is_successful", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("MARKETING", "Marketing Agent"),
                            ("COMMUNITY", "Community Agent"),
                            ("ANALYTICS", "Analytics Agent"),
                            ("LAUNCH_GUIDE", "Launch Guide Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("template", models.TextField()),
                ("variables", models.JSONField(default=list)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
