# Generated by Django 4.2.14 on 2025-08-16 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ai_agents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiprompttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to="ai_agents.aiagent",
            ),
        ),
        migrations.AddField(
            model_name="aiinteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiconversationcontext",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contexts",
                to="ai_agents.aiagent",
            ),
        ),
        migrations.AddField(
            model_name="aiconversationcontext",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_contexts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="aiagentmetrics",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to="ai_agents.aiagent",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiagent",
            unique_together={("name", "agent_type")},
        ),
        migrations.AlterUniqueTogether(
            name="aiprompttemplate",
            unique_together={("name", "agent_type")},
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["user", "timestamp"], name="ai_agents_a_user_id_99cb72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["agent", "timestamp"], name="ai_agents_a_agent_i_e26dcb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversationcontext",
            index=models.Index(
                fields=["user", "agent", "is_active"],
                name="ai_agents_a_user_id_e36bef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversationcontext",
            index=models.Index(
                fields=["expires_at"], name="ai_agents_a_expires_617ff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiagentmetrics",
            index=models.Index(
                fields=["agent", "date"], name="ai_agents_a_agent_i_ae821e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiagentmetrics",
            unique_together={("agent", "date")},
        ),
    ]
