[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Solidity compiler settings - updated for Core DAO
solc_version = "0.8.24"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = true

# Test settings
verbosity = 3
fuzz_runs = 1000
fuzz_max_test_rejects = 65536

# Gas settings
gas_limit = 9223372036854775807
gas_price = 20000000000

# Allow forge scripts to write deployment artifacts under ./deployments
fs_permissions = [
    { access = "read", path = "./" },
    { access = "read-write", path = "./deployments" }
]

# Core DAO network configurations
[rpc_endpoints]
core_testnet = "https://rpc.test2.btcs.network"
local = "http://127.0.0.1:8545"

[etherscan]
core_testnet = { key = "${CORE_API_KEY}", url = "https://scan.test.btcs.network/api" }

# Environment variables for deployment

[profile.core_testnet]
eth_rpc_url = "${CORE_TESTNET_RPC}"
private_key = "${TESTNET_PRIVATE_KEY}"
etherscan_api_key = "${CORE_API_KEY}"

[profile.local]
eth_rpc_url = "http://127.0.0.1:8545"
private_key = "${LOCAL_PRIVATE_KEY}"

# Gas optimization
[profile.optimized]
optimizer = true
optimizer_runs = 10000
via_ir = true

# Testing profile
[profile.test]
verbosity = 4
gas_reports = ["*"]
gas_reports_ignore = ["**/test/**/*", "**/script/**/*"]